-- câu 8
ALTER TABLE SANPHAM 
ADD CONSTRAINT SANPHAM_GIA 
CHECK(GIA > 500)
--câu 9

--câu 10
ALTER TABLE KHACHHANG 
ADD CONSTRAINT CHECK_NGDK 
CHECK (NGDK>NGSINH)
--câu 11
CREATE TRIGGER UPDATE_c11
ON KHACHHANG
FOR UPDATE
AS
 DECLARE @NgDK SMALLDATETIME, 
   @NgHD SMALLDATETIME

 SELECT @NgDK=NgDK
 FROM  INSERTED
 
 IF(@NGDK>ANY(SELECT NGHD
    FROM  HOADON A, INSERTED I
    WHERE A.MAKH=I.MAKH))
  BEGIN
   ROLLBACK TRAN
   PRINT 'ERROR!Ngày Đăng kí Phải nhỏ hơn ngày hóa đơn.'
  END
 ELSE
  PRINT' SUCCESSFUL'

CREATE TRIGGER HD_C11
ON HOADON
FOR INSERT,UPDATE
AS
 DECLARE @NGDK SMALLDATETIME, 
   @NGHD SMALLDATETIME

 SELECT @NGDK=NGDK,@NGHD=NGHD
 FROM  INSERTED I, KHACHHANG A
 WHERE I.MAKH=A.MAKH

 IF @NgHD<@NgDK
  BEGIN
   ROLLBACK TRAN
   PRINT 'ERROR!Ngày Hóa Đơn Phải Lớn Hơn Ngày Đăng Kí'
  END
 ELSE
  PRINT' SUCCESSFUL'

  --câu 12

  CREATE TRIGGER UPDATE_NV_C12
ON NHANVIEN
FOR UPDATE
AS
 DECLARE @NGVL SMALLDATETIME, 
   @NGHD SMALLDATETIME

 SELECT @NGVL=NGVL
 FROM  INSERTED
 
 IF(@NGVL>ANY(SELECT NGHD
    FROM  HOADON A, INSERTED I
    WHERE A.MANV=I.MANV))
  BEGIN
   ROLLBACK TRAN
   PRINT 'ERROR!Ngày vào làm phải nhỏ hơn Ngày Hóa Đơn'
  END
 ELSE
  PRINT' SUCCESSFUL'

CREATE TRIGGER HD_C12
ON HOADON
FOR INSERT,UPDATE
AS
 DECLARE @NGVL SMALLDATETIME, 
   @NGHD SMALLDATETIME

 SELECT @NGVL=NGVL,@NGHD=NGHD
 FROM  INSERTED I, NHANVIEN A
 WHERE I.MANV=A.MANV

 IF @NGHD<@NGVL
  BEGIN
   ROLLBACK TRAN
   PRINT 'ERROR!Ngày Hóa Đơn phải lớn hơn ngày Ngày vào làm.'
  END
 ELSE
  PRINT' SUCCESSFUL'
 
--câu 13

CREATE TRIGGER CTHD_C13
ON CTHD
FOR DELETE,UPDATE
AS
 DECLARE @SL  INT,
   @SOHD INT
 SELECT @SL=COUNT(A.SOHD),@SOHD=D.SOHD
 FROM  DELETED D,CTHD A
 WHERE A.SOHD=D.SOHD
 GROUP BY  D.SOHD
 IF(@SL<1)
  BEGIN
   DELETE FROM HOADON
   WHERE  SOHD=@SOHD
   PRINT 'DA DELETE CTHD CUOI CUNG CUA HOADON TREN'
  END 
CREATE TRIGGER HOADON_C13
ON HOADON
FOR INSERT
AS
 DECLARE @SOHD INT
 SELECT @SOHD=SOHD
 FROM  INSERTED
 
 UPDATE CTHD
 SET  MASP='NONE',SL=0
 WHERE SOHD=@SOHD

 PRINT 'SUCCESSFUL! DE NGHI UPDATE LAI CTHD(MAC DINH:MASP="NONE", SL=0)'

 --câu 14
 CREATE TRIGGER INSERT_HOADON_C14
ON HOADON
FOR INSERT
AS
 UPDATE HOADON
 SET  TRIGIA=0
 WHERE SOHD=(SELECT  SOHD
    FROM  INSERTED)
 PRINT'DA INSERT 1 HOADON VOI TRIGIA BAN DAU LA 0 VND' 
 -------------
CREATE TRIGGER UPDATE_HOADON_C14
ON HOADON
FOR INSERT
AS
 UPDATE HOADON
 SET  TRIGIA=(SELECT TRIGIA
     FROM DELETED)
 WHERE SOHD=(SELECT  SOHD
    FROM  INSERTED)
 PRINT'DA UPDATE 1 HOADON VOI TRIGIA KHONG THAY DOI'
 -------------
CREATE TRIGGER INSERT_CTHD_C14
ON CTHD
FOR INSERT
AS
 DECLARE  @SL  INT,
   @GIA  MONEY,
   @SOHD INT

 SELECT @GIA=GIA,@SL=SL,@SOHD=SOHD
 FROM  INSERTED A, SANPHAM B
 WHERE A.MASP=B.MASP

 UPDATE HOADON
 SET  TRIGIA=TRIGIA+@SL*@GIA
  PRINT'DA INSERT 1 CTHD VA UPDATE LAI TRIGIA CUA HOADON TUONG UNG'
 --------------
CREATE TRIGGER DELETE_CTHD_C14
ON CTHD
FOR DELETE
AS
 DECLARE  @SL  INT,
   @GIA  MONEY,
   @SOHD INT

 SELECT @GIA=GIA,@SL=SL,@SOHD=SOHD
 FROM  DELETED A, SANPHAM B
 WHERE A.MASP=B.MASP

 UPDATE HOADON
 SET  TRIGIA=TRIGIA-@SL*@GIA
  PRINT'DA DELETE 1 CTHD VA UPDATE LAI TRIGIA CUA HOADON TUONG UNG'
 -------------------
CREATE TRIGGER UPDATE_CTHD_C14
ON CTHD
FOR UPDATE
AS
 DECLARE  @SL_CU INT,
   @SL_MOI INT,   
   @GIA_CU MONEY,
   @GIA_MOI MONEY,
   @SOHD_CU INT,
   @SOHD_MOI INT

 SELECT @GIA_CU=GIA,@SL_CU=SL,@SOHD_CU=SOHD
 FROM  DELETED A, SANPHAM B
 WHERE A.MASP=B.MASP
 
 SELECT @GIA_MOI=GIA,@SL_MOI=SL,@SOHD_MOI=SOHD
 FROM  INSERTED A, SANPHAM B
 WHERE A.MASP=B.MASP

 IF(@SOHD_CU=@SOHD_MOI)
  BEGIN
   UPDATE HOADON
   SET  TRIGIA=TRIGIA+@SL_MOI*@GIA_MOI-@SL_CU*@GIA_CU
   WHERE SOHD=@SOHD_CU
  END
 ELSE
  BEGIN
   UPDATE HOADON
   SET  TRIGIA=TRIGIA-@SL_CU*@GIA_CU
   WHERE SOHD=@SOHD_CU

   UPDATE HOADON
   SET  TRIGIA=TRIGIA+@SL_MOI*@GIA_MOI
   WHERE SOHD=@SOHD_MOI
  END
 PRINT'DA UPDATE 1 CTHD VA UPDATE LAI TRIGIA CUA HOADON TUONG UNG'
 -------------------
CREATE TRIGGER UPDATE_HOADON_C14
ON  HOADON
FOR  INSERT
AS
 DECLARE @GIA_CU MONEY,
   @GIA_MOI MONEY,
   @SOHD INT,
   @SL  INT
   
 SELECT @GIA_CU=GIA
 FROM  DELETED
 SELECT @GIA_MOI=GIA
 FROM  INSERTED

 SELECT @SOHD=SOHD,@SL=SL
 FROM  INSERTED A, CTHD B
 WHERE A.MASP=B.MASP

 UPDATE HOADON
 SET  TRIGIA=TRIGIA+@SL*(@GIA_MOI-@GIA_CU) 
 WHERE SOHD=@SOHD
  PRINT'DA UPDATE 1 HOADON VOI TRIGIA KHONG THAY DOI'